/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Project1RouteImport } from './routes/project1'
import { Route as IndexRouteImport } from './routes/index'

const Project1Route = Project1RouteImport.update({
  id: '/project1',
  path: '/project1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project1': typeof Project1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project1': typeof Project1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project1': typeof Project1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/project1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project1'
  id: '__root__' | '/' | '/project1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Project1Route: typeof Project1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project1': {
      id: '/project1'
      path: '/project1'
      fullPath: '/project1'
      preLoaderRoute: typeof Project1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Project1Route: Project1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
